</div>
<!-- footer template - added to the bottom of every file -->
<footer class="footer mt-5 py-3 text-center">
    <div class="container">
        <p class="mb-1"><strong>PetWatch</strong> | Hamid Aziz</p>
    </div>
</footer>

<!-- Bootstrap JS for models and dropdowns etc. -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>
